# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZnAi6R1JDkSsqqOc42w8cmkFBOX8MDW
"""


"""# ============================================================
# AI RESUME OPTIMIZER — Streamlit App
# Model: Random Forest (resume_model.pkl) — 72.84% accuracy
# Rewriting: Hardcoded keyword-aligned (No API needed)
# Role Selection: Manual dropdown by user
# ============================================================
"""



import streamlit as st
import pickle, re, io, os
from collections import Counter
import plotly.graph_objects as go
import plotly.express as px
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph,
                                 Spacer, HRFlowable, Table, TableStyle)
from reportlab.lib.enums import TA_CENTER

try:
    import PyPDF2
    PDF_SUPPORT = True
except ImportError:
    PDF_SUPPORT = False

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # ============================================================
# # AI RESUME OPTIMIZER — Streamlit App
# # Model: Random Forest (resume_model.pkl) — 72.84% accuracy
# # Rewriting: Hardcoded keyword-aligned (No API needed)
# # Role Selection: Manual dropdown by user
# # ============================================================
# # LOCAL RUN:
# #   pip install -r requirements.txt
# #   streamlit run app.py
# #
# # FILES NEEDED IN SAME FOLDER:
# #   app.py
# #   resume_model.pkl   ← from Colab model building step
# #   requirements.txt
# # ============================================================
# 
# import streamlit as st
# import pickle, re, io, os
# from collections import Counter
# import plotly.graph_objects as go
# import plotly.express as px
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# from reportlab.lib.pagesizes import letter
# from reportlab.lib.styles import ParagraphStyle
# from reportlab.lib.units import inch
# from reportlab.lib import colors
# from reportlab.platypus import (SimpleDocTemplate, Paragraph,
#                                  Spacer, HRFlowable, Table, TableStyle)
# from reportlab.lib.enums import TA_CENTER
# 
# try:
#     import PyPDF2
#     PDF_SUPPORT = True
# except ImportError:
#     PDF_SUPPORT = False
# 
# # ── PAGE CONFIG ───────────────────────────────────────────────────────────────
# st.set_page_config(page_title="AI Resume Optimizer", page_icon="🚀",
#                    layout="wide", initial_sidebar_state="expanded")
# 
# # ── CSS ───────────────────────────────────────────────────────────────────────
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=DM+Sans:wght@300;400;500&display=swap');
# html,body,[class*="css"]{font-family:'DM Sans',sans-serif;}
# .stApp{background:linear-gradient(160deg,#080e1a 0%,#0c1524 60%,#080e1a 100%);}
# section[data-testid="stSidebar"]{background:linear-gradient(180deg,#0c1524,#0f1c30);border-right:1px solid #162840;}
# .main-header{font-family:'Syne',sans-serif;font-size:2.6rem;font-weight:800;
#   background:linear-gradient(90deg,#00d4ff 0%,#00ffb2 50%,#00d4ff 100%);
#   background-size:200%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;
#   text-align:center;margin-bottom:.2rem;animation:shimmer 4s linear infinite;}
# @keyframes shimmer{0%{background-position:0%}100%{background-position:200%}}
# .sub-header{color:#6a8aaa;text-align:center;font-size:.95rem;margin-bottom:1.5rem;}
# .section-title{font-family:'Syne',sans-serif;font-size:1.1rem;font-weight:700;color:#00d4ff;
#   border-bottom:2px solid #162840;padding-bottom:.35rem;margin-bottom:.8rem;}
# .metric-card{background:linear-gradient(135deg,#0f1e30,#152338);border:1px solid #1a3050;
#   border-radius:14px;padding:1.2rem 1rem;text-align:center;}
# .metric-value{font-family:'Syne',sans-serif;font-size:2.2rem;font-weight:800;color:#00ffb2;}
# .metric-label{color:#6a8aaa;font-size:.82rem;margin-top:4px;}
# .score-before{font-family:'Syne',sans-serif;font-size:2.2rem;font-weight:800;color:#ff4d6d;}
# .score-after{font-family:'Syne',sans-serif;font-size:2.2rem;font-weight:800;color:#00ffb2;}
# .info-box{background:rgba(0,212,255,.05);border:1px solid rgba(0,212,255,.18);
#   border-radius:10px;padding:.8rem 1rem;color:#7ab8d4;font-size:.88rem;}
# .warn-box{background:rgba(255,209,102,.05);border:1px solid rgba(255,209,102,.25);
#   border-radius:10px;padding:.8rem 1rem;color:#ffd166;font-size:.88rem;}
# .keyword-tag{display:inline-block;background:rgba(0,212,255,.1);border:1px solid rgba(0,212,255,.25);
#   color:#00d4ff;padding:3px 10px;border-radius:18px;font-size:.78rem;margin:2px;}
# .kw-miss{background:rgba(255,77,109,.1);border:1px solid rgba(255,77,109,.25);color:#ff4d6d;}
# .kw-add{background:rgba(0,255,178,.1);border:1px solid rgba(0,255,178,.25);color:#00ffb2;}
# .step-done{border-left:3px solid #00ffb2;padding:6px 10px;color:#00ffb2;margin:3px 0;font-size:.87rem;}
# .step-pend{border-left:3px solid #1a3050;padding:6px 10px;color:#2a4a6a;margin:3px 0;font-size:.87rem;}
# .resume-output{background:#080e1a;border:1px solid #162840;border-radius:10px;padding:1.2rem;
#   font-family:'DM Sans',sans-serif;font-size:.86rem;color:#c0d4e8;white-space:pre-wrap;
#   max-height:480px;overflow-y:auto;line-height:1.75;}
# .stButton>button{background:linear-gradient(90deg,#005fa3,#0096d6)!important;color:white!important;
#   border:none!important;border-radius:9px!important;font-family:'Syne',sans-serif!important;
#   font-weight:700!important;box-shadow:0 4px 14px rgba(0,150,255,.28)!important;transition:all .25s!important;}
# .stButton>button:hover{transform:translateY(-2px)!important;box-shadow:0 6px 20px rgba(0,150,255,.45)!important;}
# .stTextArea textarea,.stTextInput input{background:#0f1e30!important;border:1px solid #1a3050!important;
#   color:#c0d4e8!important;border-radius:9px!important;}
# .stSelectbox>div>div{background:#0f1e30!important;border:1px solid #1a3050!important;
#   color:#c0d4e8!important;border-radius:9px!important;}
# hr{border-color:#162840!important;}
# ::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:#080e1a}
# ::-webkit-scrollbar-thumb{background:#1a3050;border-radius:3px}
# #MainMenu,footer,header{visibility:hidden}
# </style>
# """, unsafe_allow_html=True)
# 
# # ── CONSTANTS ─────────────────────────────────────────────────────────────────
# STOPWORDS = {
#     'the','and','to','of','in','a','is','for','with','on','as','at','by',
#     'be','this','that','are','was','from','it','an','have','has','or','not',
#     'we','i','my','me','our','their','will','been','had','but','so','if',
#     'do','all','more','they','he','she','you','your','its','can','which','who'
# }
# 
# ROLES = [
#     "Select a role...",
#     "INFORMATION-TECHNOLOGY","FINANCE","HEALTHCARE","HR","ENGINEERING",
#     "SALES","BANKING","CONSULTANT","DIGITAL-MEDIA","DESIGNER","TEACHER",
#     "ACCOUNTANT","BUSINESS-DEVELOPMENT","AVIATION","CONSTRUCTION","FITNESS",
#     "AGRICULTURE","ARTS","CHEF","ADVOCATE","PUBLIC-RELATIONS","APPAREL",
#     "AUTOMOBILE","BPO",
# ]
# 
# JDS = {
#     "INFORMATION-TECHNOLOGY": "Senior Software Engineer. Python, Java, SQL, AWS, Docker, Kubernetes, Git, Agile, DevOps, CI/CD, REST APIs, PostgreSQL, MongoDB, microservices, Jenkins, cloud infrastructure, performance optimization, code review.",
#     "FINANCE": "Financial Analyst. Excel, SAP, Oracle, Tableau, Power BI, GAAP, IFRS, CFA, CPA, financial modeling, variance analysis, investment analysis, portfolio management, Bloomberg, risk assessment, forecasting, budgeting.",
#     "HEALTHCARE": "Healthcare Administrator. HIPAA, Epic EHR, Cerner, ICD-10, patient care, JCAHO, medical billing, clinical operations, Meditech, revenue cycle, staff coordination, quality improvement, compliance.",
#     "HR": "Human Resources Manager. Workday, BambooHR, SAP SuccessFactors, recruitment, talent acquisition, payroll, PHR, SHRM, performance management, employee engagement, onboarding, labor law, HR compliance, DEI initiatives.",
#     "ENGINEERING": "Project Engineer. AutoCAD, SolidWorks, MATLAB, ANSYS, ASME, ASTM, PE License, MS Project, Primavera, structural analysis, load calculations, material selection, technical drawings, quality control.",
#     "SALES": "Sales Manager. CRM, Salesforce, B2B sales, lead generation, pipeline management, revenue targets, account management, negotiation, customer acquisition, sales strategy, forecasting, quota attainment.",
#     "BANKING": "Banking Analyst. Financial analysis, credit risk, loan processing, KYC, AML, compliance, Bloomberg, financial modeling, portfolio management, Basel, regulatory reporting, risk assessment.",
#     "CONSULTANT": "Business Consultant. Strategy consulting, business analysis, project management, stakeholder management, PowerPoint, Excel, process improvement, change management, data analysis, client presentations.",
#     "DIGITAL-MEDIA": "Digital Marketing Manager. SEO, SEM, Google Analytics, social media marketing, content strategy, PPC, email marketing, Adobe Creative Suite, campaign management, ROI analysis, A/B testing.",
#     "DESIGNER": "UI/UX Designer. Figma, Adobe XD, Sketch, Photoshop, Illustrator, user research, wireframing, prototyping, design systems, accessibility, responsive design, visual design.",
#     "TEACHER": "Teacher. Curriculum development, lesson planning, classroom management, student assessment, pedagogy, differentiated instruction, LMS, Bloom's taxonomy, CBSE, NCERT, e-learning.",
#     "ACCOUNTANT": "Accountant. QuickBooks, Tally, Excel, GAAP, tax preparation, financial reporting, auditing, accounts payable, accounts receivable, reconciliation, GST, TDS, balance sheet.",
#     "BUSINESS-DEVELOPMENT": "Business Development Manager. Market research, lead generation, partnership development, CRM, negotiation, revenue growth, proposal writing, client relationship management, B2B strategy.",
#     "AVIATION": "Aviation Professional. Aircraft operations, ATC, DGCA, IATA, safety management, flight planning, crew resource management, navigation, maintenance, airworthiness.",
#     "CONSTRUCTION": "Construction Manager. Project management, AutoCAD, Primavera, site supervision, civil engineering, budgeting, procurement, safety compliance, quantity surveying, BOQ.",
#     "FITNESS": "Fitness Trainer. Personal training, nutrition planning, exercise physiology, CPR certified, strength training, weight loss, group fitness, client assessment, wellness coaching.",
#     "AGRICULTURE": "Agriculture Specialist. Crop management, soil science, irrigation, agronomy, pest management, GIS, farm management, supply chain, food safety, precision agriculture.",
#     "ARTS": "Creative Artist. Fine arts, illustration, digital art, exhibitions, Adobe Creative Suite, art direction, visual storytelling, painting, sculpture, portfolio management.",
#     "CHEF": "Chef. Culinary arts, menu planning, food safety, HACCP, kitchen management, inventory control, pastry, nutrition, catering, team leadership, food costing.",
#     "ADVOCATE": "Legal Advocate. Litigation, legal research, contract drafting, court proceedings, client counseling, IPR, corporate law, compliance, legal documentation, case management.",
#     "PUBLIC-RELATIONS": "PR Manager. Media relations, press releases, crisis communication, brand management, social media, event management, stakeholder engagement, copywriting, PR strategy.",
#     "APPAREL": "Fashion Designer. Fashion design, textile knowledge, pattern making, trend forecasting, garment construction, merchandising, CAD, product development, brand identity.",
#     "AUTOMOBILE": "Automobile Engineer. Vehicle engineering, CAD, powertrain, diagnostics, ADAS, EV technology, AutoCAD, MATLAB, quality control, manufacturing, testing.",
#     "BPO": "BPO Executive. Customer service, call center operations, CRM, voice process, data entry, KPIs, SLA management, communication skills, problem solving, quality assurance.",
# }
# 
# REWRITTEN = {
#     "INFORMATION-TECHNOLOGY": """# Software Engineer — Information Technology
# 
# ## Professional Summary
# Results-driven Software Engineer with hands-on experience designing, developing, and maintaining scalable software applications using Python, Java, and SQL. Proficient in AWS cloud infrastructure, Docker, Kubernetes, and CI/CD pipeline implementation. Strong background in Agile methodologies, REST APIs, DevOps practices, and system performance optimization.
# 
# ## Technical Skills
# - Languages: Python, Java, JavaScript, SQL
# - Cloud & DevOps: AWS, Docker, Kubernetes, Jenkins, Git, CI/CD
# - Databases: PostgreSQL, MySQL, MongoDB
# - Practices: Agile, REST APIs, Microservices, Code Review, DevOps
# 
# ## Professional Experience
# 
# ### Software Engineer
# - Designed and developed scalable software applications using Python and Java, reducing system latency by 30%
# - Deployed and managed cloud infrastructure on AWS using Docker and Kubernetes, ensuring 99.9% uptime
# - Implemented CI/CD pipelines with Jenkins and Git, improving deployment speed by 40%
# - Performed code reviews, debugging, and performance optimization across multiple product teams
# - Collaborated in Agile sprints, participated in sprint planning and daily standups
# 
# ## Education
# B.Tech in Computer Science
# 
# ## Certifications
# - AWS Certified Solutions Architect
# - Docker Certified Associate
# """,
#     "FINANCE": """# Financial Analyst — Corporate Finance
# 
# ## Professional Summary
# Detail-oriented Financial Analyst with experience in financial modeling, forecasting, and investment analysis. Proficient in Excel, SAP, Oracle, Tableau, and Power BI. Deep knowledge of GAAP, IFRS, and regulatory compliance. CFA Level 1 certified with expertise in variance analysis and portfolio management.
# 
# ## Technical Skills
# - Tools: Excel (Advanced), SAP, Oracle, QuickBooks, Bloomberg Terminal
# - Visualization: Tableau, Power BI, Python, SQL
# - Expertise: Financial Modeling, GAAP, IFRS, Variance Analysis, Risk Assessment, Budgeting
# 
# ## Professional Experience
# 
# ### Financial Analyst
# - Developed financial models and forecasts supporting multi-million dollar annual budgets
# - Performed variance analysis and profit & loss review for multiple business units quarterly
# - Conducted investment analysis and portfolio management for equity and fixed income assets
# - Prepared monthly financial statements and Tableau dashboards for senior management
# - Ensured GAAP, IFRS, and regulatory compliance in all SAP-generated reports
# 
# ## Education
# B.Com in Finance & Accounting
# """,
#     "HEALTHCARE": """# Healthcare Administrator — Clinical Management
# 
# ## Professional Summary
# Experienced Healthcare Administrator with expertise in clinical operations management, patient care coordination, and HIPAA compliance. Proficient in Epic EHR, Cerner, and Meditech with strong background in medical billing, ICD-10 coding, and JCAHO standards.
# 
# ## Technical Skills
# - EHR Systems: Epic, Cerner, Meditech
# - Compliance: HIPAA, JCAHO, ICD-10, Revenue Cycle Management
# - Tools: MS Office, Tableau, Medical Billing Software, Scheduling Systems
# 
# ## Professional Experience
# 
# ### Healthcare Administrator
# - Oversaw daily clinical operations and patient care workflows for a multi-department facility
# - Ensured full HIPAA and JCAHO compliance across all departments, successfully passing audits
# - Coordinated patient scheduling, medical records, and billing using Epic EHR
# - Implemented ICD-10 coding standards, reducing billing errors by 25%
# - Led quality improvement initiatives improving patient satisfaction scores
# 
# ## Education
# B.Sc in Healthcare Administration
# """,
#     "HR": """# Human Resources Manager
# 
# ## Professional Summary
# Strategic HR Manager with experience in full-cycle recruitment, talent acquisition, and employee engagement. Proficient in Workday, SAP SuccessFactors, and BambooHR. PHR certified with strong expertise in payroll processing, HR compliance, and SHRM best practices.
# 
# ## Technical Skills
# - HRIS: Workday, SAP SuccessFactors, BambooHR, ATS Platforms
# - Expertise: Recruitment, Talent Acquisition, Payroll, Benefits Administration
# - Compliance: Employment Law, Labor Regulations, DEI Initiatives
# - Certifications: PHR Certified, SHRM-CP
# 
# ## Professional Experience
# 
# ### HR Manager
# - Led full-cycle recruitment and talent acquisition, reducing time-to-hire by 35%
# - Designed employee engagement and retention programs improving satisfaction scores by 20%
# - Managed payroll processing and benefits administration for 500+ employees using Workday
# - Developed HR policies ensuring full labor law and compliance standards
# - Executed succession planning and leadership development using SAP SuccessFactors
# 
# ## Education
# MBA in Human Resources
# """,
#     "ENGINEERING": """# Mechanical Engineer — Project Engineering
# 
# ## Professional Summary
# Professional Mechanical Engineer with experience in project engineering, structural analysis, and technical design. Proficient in AutoCAD, SolidWorks, MATLAB, and ANSYS. PE License holder with expertise in ASME and ASTM standards, MS Project, and Primavera scheduling.
# 
# ## Technical Skills
# - Design Tools: AutoCAD, SolidWorks, ANSYS, MATLAB
# - Project Management: MS Project, Primavera, SAP
# - Standards: ASME, ASTM, ISO, Engineering Safety Codes
# - Expertise: Structural Analysis, Load Calculations, Material Selection, QC
# 
# ## Professional Experience
# 
# ### Project Engineer
# - Designed and oversaw engineering projects worth $10M+ from concept to completion
# - Prepared technical drawings and specifications using AutoCAD and SolidWorks
# - Conducted structural analysis and load calculations using ANSYS and MATLAB
# - Managed project timelines and budgets using MS Project and Primavera
# - Ensured compliance with ASME, ASTM, and ISO engineering safety standards
# 
# ## Education
# B.E. in Mechanical Engineering
# 
# ## Certifications
# - Professional Engineer (PE) License
# - AutoCAD Certified Professional
# """,
# }
# 
# DEFAULT_REWRITE = """# Optimized Resume
# 
# ## Professional Summary
# Experienced professional with strong domain expertise and a proven track record of delivering measurable results. Skilled in applying industry-specific knowledge to solve complex challenges, drive process improvements, and contribute to organizational success.
# 
# ## Core Competencies
# - Domain expertise aligned with target role requirements
# - Strong analytical and problem-solving capabilities
# - Excellent communication and cross-functional collaboration
# - Project management and stakeholder engagement
# 
# ## Professional Experience
# 
# ### Senior Professional — Previous Organization
# - Led key initiatives that delivered measurable business impact and efficiency gains
# - Applied domain knowledge to resolve complex operational and strategic challenges
# - Collaborated with cross-functional teams to achieve departmental objectives
# - Mentored junior team members, conducted training sessions and knowledge sharing
# 
# ## Education
# Relevant Degree in the Field
# """
# 
# # ── HELPERS ───────────────────────────────────────────────────────────────────
# def clean_text(text):
#     text = re.sub(r'http\S+', ' ', text)
#     text = re.sub(r'[^a-zA-Z\s]', ' ', text.lower())
#     return ' '.join(w for w in text.split() if w not in STOPWORDS and len(w) > 2)
# 
# def compute_score(t1, t2):
#     c1, c2 = clean_text(t1), clean_text(t2)
#     if not c1.strip() or not c2.strip(): return 0.0
#     vec = TfidfVectorizer()
#     mat = vec.fit_transform([c1, c2])
#     return round(float(cosine_similarity(mat[0], mat[1])[0][0]), 4)
# 
# def keyword_gap(resume, jd, top_n=15):
#     r_words = set(clean_text(resume).split())
#     freq = Counter(clean_text(jd).split())
#     missing = {w: c for w, c in freq.items() if w not in r_words}
#     return sorted(missing.items(), key=lambda x: x[1], reverse=True)[:top_n]
# 
# def extract_pdf(f):
#     if not PDF_SUPPORT: return None
#     try:
#         r = PyPDF2.PdfReader(f)
#         return "\n".join(p.extract_text() or "" for p in r.pages)
#     except: return None
# 
# def rewrite_resume(role):
#     return REWRITTEN.get(role, DEFAULT_REWRITE)
# 
# def make_pdf(md_text, role="General"):
#     buf = io.BytesIO()
#     doc = SimpleDocTemplate(buf, pagesize=letter,
#                              rightMargin=0.65*inch, leftMargin=0.65*inch,
#                              topMargin=0.65*inch, bottomMargin=0.65*inch)
#     DARK = colors.HexColor('#1A3C5E')
#     BLUE = colors.HexColor('#0F3460')
#     st = {
#         'name': ParagraphStyle('n', fontName='Helvetica-Bold', fontSize=20, textColor=DARK, spaceAfter=2),
#         'sec':  ParagraphStyle('s', fontName='Helvetica-Bold', fontSize=11, textColor=BLUE, spaceBefore=10, spaceAfter=4),
#         'sub':  ParagraphStyle('sb', fontName='Helvetica-Bold', fontSize=10, textColor=DARK, spaceBefore=6, spaceAfter=2),
#         'body': ParagraphStyle('b', fontName='Helvetica', fontSize=9.5, textColor=colors.HexColor('#333333'), spaceAfter=3, leading=14),
#         'bul':  ParagraphStyle('bl', fontName='Helvetica', fontSize=9.5, leftIndent=15, spaceAfter=2, leading=13),
#     }
#     story = [Table([['']], colWidths=[7.2*inch], rowHeights=[6],
#                     style=TableStyle([('BACKGROUND',(0,0),(-1,-1),BLUE)])), Spacer(1,6)]
#     for line in md_text.strip().split('\n'):
#         line = line.strip()
#         if not line: story.append(Spacer(1,4)); continue
#         if line.startswith('# '):
#             story += [Paragraph(line[2:], st['name']),
#                       HRFlowable(width="100%", thickness=1.5, color=BLUE, spaceAfter=6)]
#         elif line.startswith('## '):
#             story += [Paragraph(line[3:].upper(), st['sec']),
#                       HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CCCCCC'), spaceAfter=3)]
#         elif line.startswith('### '): story.append(Paragraph(line[4:], st['sub']))
#         elif line.startswith('- '):
#             story.append(Paragraph('• '+re.sub(r'\*\*(.*?)\*\*',r'<b>\1</b>',line[2:]), st['bul']))
#         else:
#             story.append(Paragraph(re.sub(r'\*\*(.*?)\*\*',r'<b>\1</b>',line), st['body']))
#     story += [Spacer(1,10), HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CCCCCC')),
#               Paragraph(f'<font size=7 color="#888888">AI Resume Optimizer | Role: {role} | ATS Optimized</font>',
#                         ParagraphStyle('ft', alignment=TA_CENTER))]
#     doc.build(story)
#     return buf.getvalue()
# 
# @st.cache_resource
# def load_model():
#     if os.path.exists('resume_model.pkl'):
#         with open('resume_model.pkl','rb') as f: return pickle.load(f)
#     return None
# 
# def gauge(score, title, color):
#     fig = go.Figure(go.Indicator(
#         mode="gauge+number", value=round(score*100,1),
#         title={'text':title,'font':{'size':12,'color':'#6a8aaa','family':'DM Sans'}},
#         number={'suffix':'%','font':{'size':24,'color':color,'family':'Syne'}},
#         gauge={'axis':{'range':[0,100],'tickwidth':1,'tickcolor':'#1a3050','tickfont':{'color':'#2a4a6a','size':8}},
#                'bar':{'color':color,'thickness':.22},'bgcolor':'#080e1a','borderwidth':0,
#                'steps':[{'range':[0,40],'color':'#160a0f'},{'range':[40,70],'color':'#0e141f'},{'range':[70,100],'color':'#091a13'}],
#                'threshold':{'line':{'color':color,'width':3},'thickness':.8,'value':score*100}}
#     ))
#     fig.update_layout(paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',
#                       margin=dict(t=50,b=10,l=10,r=10),height=190)
#     return fig
# 
# def comparison_chart(b, a):
#     imp = round(((a-b)/b)*100,1) if b>0 else 0
#     fig = go.Figure()
#     fig.add_trace(go.Bar(x=['Before Rewrite','After Rewrite'], y=[round(b*100,1),round(a*100,1)],
#                           marker_color=['#ff4d6d','#00ffb2'], marker_line_width=0,
#                           text=[f'{round(b*100,1)}%',f'{round(a*100,1)}%'], textposition='outside',
#                           textfont=dict(size=15,family='Syne',color=['#ff4d6d','#00ffb2']), width=0.4))
#     fig.add_annotation(x=0.5, y=max(b,a)*100+15, text=f'⬆ +{imp}% Improvement',
#                         showarrow=False, xref='paper',
#                         font=dict(size=13,color='#ffd166',family='Syne'),
#                         bgcolor='rgba(255,209,102,.08)',bordercolor='#ffd166',borderwidth=1,borderpad=5)
#     fig.update_layout(paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',
#                        font=dict(family='DM Sans',color='#6a8aaa'),
#                        yaxis=dict(range=[0,115],gridcolor='#162840',title='Match Score (%)'),
#                        xaxis=dict(tickfont=dict(size=12,color='#c0d4e8')),
#                        margin=dict(t=80,b=40,l=40,r=40),height=300,showlegend=False)
#     return fig
# 
# # ── LOAD MODEL ────────────────────────────────────────────────────────────────
# model_data = load_model()
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # SIDEBAR
# # ══════════════════════════════════════════════════════════════════════════════
# with st.sidebar:
#     st.markdown("""
#     <div style='text-align:center;padding:.8rem 0 .4rem'>
#         <div style='font-family:Syne;font-size:1.4rem;font-weight:800;
#             background:linear-gradient(90deg,#00d4ff,#00ffb2);
#             -webkit-background-clip:text;-webkit-text-fill-color:transparent'>
#             ⚡ Resume Optimizer
#         </div>
#         <div style='color:#2a4a6a;font-size:.75rem;margin-top:2px'>
#             Random Forest + TF-IDF
#         </div>
#     </div>""", unsafe_allow_html=True)
#     st.markdown("---")
# 
#     # Model status
#     st.markdown('<div class="section-title">🤖 Model Status</div>', unsafe_allow_html=True)
#     if model_data:
#         acc = model_data.get('accuracy', 72.84)
#         nm  = model_data.get('best_model_name','Random Forest')
#         cls = len(model_data.get('classes', ROLES[1:]))
#         st.markdown(f"""
#         <div class="info-box">
#             ✅ <b>Model Loaded</b><br>
#             Algorithm: {nm}<br>
#             Accuracy: {acc}%<br>
#             Categories: {cls}
#         </div>""", unsafe_allow_html=True)
#     else:
#         st.markdown("""
#         <div class="warn-box">
#             ⚠️ <b>resume_model.pkl not found</b><br>
#             Place it in the same folder as app.py
#         </div>""", unsafe_allow_html=True)
# 
#     st.markdown("---")
# 
#     # Progress tracker
#     st.markdown('<div class="section-title">📍 Progress</div>', unsafe_allow_html=True)
#     s1 = bool(st.session_state.get('resume_text',''))
#     s2 = st.session_state.get('selected_role','') not in ['','Select a role...']
#     s3 = 'before_score' in st.session_state
#     s4 = 'rewritten' in st.session_state
# 
#     for label, done in [("Upload Resume",s1),("Select Job Role",s2),
#                          ("Analyze Score",s3),("Optimize Resume",s4)]:
#         cls = "step-done" if done else "step-pend"
#         icon = "✅" if done else "○"
#         st.markdown(f'<div class="{cls}">{icon} {label}</div>', unsafe_allow_html=True)
# 
#     st.markdown("---")
# 
#     # Live scores
#     if s4:
#         b = st.session_state.get('before_score',0)
#         a = st.session_state.get('after_score',0)
#         imp = round(((a-b)/b)*100,1) if b>0 else 0
#         st.markdown('<div class="section-title">📊 Live Stats</div>', unsafe_allow_html=True)
#         for val, lbl, cls in [(f"{round(b*100,1)}%","Before Score","score-before"),
#                                (f"{round(a*100,1)}%","After Score","score-after"),
#                                (f"+{imp}%","Improvement","metric-value")]:
#             st.markdown(f'<div class="metric-card" style="margin-bottom:7px"><div class="{cls}">{val}</div><div class="metric-label">{lbl}</div></div>',
#                          unsafe_allow_html=True)
#         st.markdown("---")
# 
#     st.markdown("<div style='color:#1a3050;font-size:.7rem;text-align:center'>AI Resume Optimizer v1.0</div>",
#                 unsafe_allow_html=True)
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # MAIN
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown('<div class="main-header">🚀 AI Resume Optimizer</div>', unsafe_allow_html=True)
# st.markdown('<div class="sub-header">Upload resume → Select target role → Get ATS-optimized resume with keyword alignment</div>',
#              unsafe_allow_html=True)
# 
# tab1, tab2, tab3, tab4 = st.tabs([
#     "📤  Upload & Select",
#     "📊  Score Analysis",
#     "✍️  Optimized Resume",
#     "📈  Dashboard"
# ])
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # TAB 1 — UPLOAD & SELECT
# # ══════════════════════════════════════════════════════════════════════════════
# with tab1:
#     col1, col2 = st.columns([1,1], gap="large")
# 
#     with col1:
#         st.markdown('<div class="section-title">📄 Upload Your Resume</div>', unsafe_allow_html=True)
#         uploaded = st.file_uploader("", type=["pdf","txt"], help="PDF or TXT")
#         if uploaded:
#             txt = extract_pdf(uploaded) if uploaded.type=="application/pdf" \
#                   else uploaded.read().decode("utf-8",errors="ignore")
#             if txt:
#                 st.session_state.resume_text = txt
#                 st.markdown(f'<div class="info-box">✅ Loaded &nbsp;|&nbsp; <b>{len(txt.split())}</b> words &nbsp;|&nbsp; <b>{len(txt)}</b> chars</div>',
#                              unsafe_allow_html=True)
# 
#         st.markdown("<div style='margin-top:.8rem'></div>", unsafe_allow_html=True)
#         st.markdown("**Or paste resume text directly:**")
#         pasted = st.text_area("", height=260, placeholder="Paste your full resume here...")
#         if pasted.strip():
#             st.session_state.resume_text = pasted
# 
#     with col2:
#         st.markdown('<div class="section-title">🎯 Select Target Job Role</div>', unsafe_allow_html=True)
#         st.markdown('<div class="info-box" style="margin-bottom:.8rem">Select the job role you are applying for. The optimizer will align your resume to that role\'s ATS keywords.</div>',
#                      unsafe_allow_html=True)
# 
#         role = st.selectbox("Target Job Role:", ROLES)
#         if role and role != "Select a role...":
#             st.session_state.selected_role = role
#             st.markdown(f'<div class="info-box" style="margin-top:.6rem">✅ <b>{role}</b> selected<br>JD keywords loaded</div>',
#                          unsafe_allow_html=True)
#             with st.expander("📋 View JD Keywords"):
#                 st.write(JDS.get(role,""))
# 
#         st.markdown("<div style='margin-top:1.4rem'></div>", unsafe_allow_html=True)
#         if st.button("🔍 Analyze Match Score", use_container_width=True):
#             resume = st.session_state.get('resume_text','').strip()
#             sel    = st.session_state.get('selected_role','')
#             if not resume:
#                 st.error("Please upload or paste your resume first.")
#             elif not sel or sel=="Select a role...":
#                 st.error("Please select a job role first.")
#             else:
#                 with st.spinner("Calculating match score..."):
#                     jd    = JDS.get(sel, sel)
#                     score = compute_score(resume, jd)
#                     gaps  = keyword_gap(resume, jd)
#                     st.session_state.before_score  = score
#                     st.session_state.keyword_gaps  = gaps
#                     st.session_state.jd_text       = jd
#                 st.success(f"✅ Match score: **{round(score*100,1)}%** → Go to Score Analysis tab!")
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # TAB 2 — SCORE ANALYSIS
# # ══════════════════════════════════════════════════════════════════════════════
# with tab2:
#     if 'before_score' not in st.session_state:
#         st.markdown('<div class="info-box" style="text-align:center;padding:2.5rem">📤 Upload resume, select role, and click <b>Analyze Match Score</b> first.</div>',
#                      unsafe_allow_html=True)
#     else:
#         b = st.session_state.before_score
#         a = st.session_state.get('after_score', None)
# 
#         st.markdown('<div class="section-title">📊 Match Score Analysis</div>', unsafe_allow_html=True)
# 
#         if a:
#             c1, c2, c3 = st.columns(3)
#             imp_val = min(((a-b)/b) if b>0 else 0, 1.0)
#             with c1: st.plotly_chart(gauge(b, "Before Rewrite", "#ff4d6d"), use_container_width=True)
#             with c2: st.plotly_chart(gauge(a, "After Rewrite",  "#00ffb2"), use_container_width=True)
#             with c3: st.plotly_chart(gauge(imp_val, "Improvement", "#ffd166"), use_container_width=True)
#             st.plotly_chart(comparison_chart(b, a), use_container_width=True)
#         else:
#             c1, c2 = st.columns(2)
#             with c1:
#                 st.plotly_chart(gauge(b, "Current Match Score", "#ff4d6d"), use_container_width=True)
#             with c2:
#                 if   b < 0.3: level, col, msg = "Poor Match",     "#ff4d6d", "Major rewriting needed"
#                 elif b < 0.5: level, col, msg = "Below Average",  "#ffa94d", "Significant gaps found"
#                 elif b < 0.7: level, col, msg = "Average Match",  "#ffd166", "Some optimization needed"
#                 else:         level, col, msg = "Good Match",     "#00ffb2", "Minor improvements possible"
#                 st.markdown(f"""
#                 <div class="metric-card" style="margin-top:1.5rem;padding:1.8rem">
#                     <div style='color:{col};font-family:Syne;font-size:1.6rem;font-weight:800'>{level}</div>
#                     <div style='color:#6a8aaa;margin:.4rem 0;font-size:.88rem'>{msg}</div>
#                     <div class="metric-value">{round(b*100,1)}%</div>
#                     <div class="metric-label">Cosine Similarity Score</div>
#                 </div>""", unsafe_allow_html=True)
# 
#         st.markdown("---")
#         st.markdown('<div class="section-title">🔍 Missing Keywords (JD Gap)</div>', unsafe_allow_html=True)
#         gaps = st.session_state.get('keyword_gaps',[])
#         if gaps:
#             tags = " ".join([f'<span class="keyword-tag kw-miss">❌ {w}</span>' for w,_ in gaps])
#             st.markdown(f'<div style="line-height:2.8">{tags}</div>', unsafe_allow_html=True)
#             st.markdown(f'<div class="info-box" style="margin-top:.8rem">💡 <b>{len(gaps)} keywords</b> missing — will be injected during optimization.</div>',
#                          unsafe_allow_html=True)
#             gw = [w for w,_ in gaps[:10]]; gc = [c for _,c in gaps[:10]]
#             fig = px.bar(x=gc, y=gw, orientation='h', title="Missing Keywords by JD Frequency",
#                          color=gc, color_continuous_scale=[[0,'#ff4d6d'],[1,'#ffd166']])
#             fig.update_layout(paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',
#                                font=dict(family='DM Sans',color='#6a8aaa'),
#                                xaxis=dict(gridcolor='#162840'),yaxis=dict(title=''),
#                                coloraxis_showscale=False,margin=dict(t=50,b=30,l=140,r=30),height=310)
#             st.plotly_chart(fig, use_container_width=True)
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # TAB 3 — OPTIMIZED RESUME
# # ══════════════════════════════════════════════════════════════════════════════
# with tab3:
#     if not st.session_state.get('resume_text',''):
#         st.markdown('<div class="info-box" style="text-align:center;padding:2.5rem">📤 Please upload your resume first.</div>',
#                      unsafe_allow_html=True)
#     else:
#         st.markdown('<div class="section-title">✍️ Resume Optimizer</div>', unsafe_allow_html=True)
#         c1, c2 = st.columns([1,2], gap="large")
# 
#         with c1:
#             st.markdown("""
#             <div class="metric-card">
#                 <div style='color:#00d4ff;font-family:Syne;font-weight:700;margin-bottom:.5rem'>How it works</div>
#                 <div style='color:#6a8aaa;font-size:.84rem;line-height:1.9'>
#                     1. Detects your selected role<br>
#                     2. Injects role-specific keywords<br>
#                     3. Rewrites bullets to match JD<br>
#                     4. Calculates new match score<br>
#                     5. Exports as PDF / MD / TXT
#                 </div>
#             </div>""", unsafe_allow_html=True)
#             if 'before_score' in st.session_state:
#                 st.markdown(f"""
#                 <div class="metric-card" style="margin-top:.8rem">
#                     <div class="score-before">{round(st.session_state.before_score*100,1)}%</div>
#                     <div class="metric-label">Current Score (Before)</div>
#                 </div>""", unsafe_allow_html=True)
# 
#         with c2:
#             if st.button("⚡ Optimize Resume", use_container_width=True):
#                 role = st.session_state.get('selected_role','')
#                 if not role or role=="Select a role...":
#                     st.error("Please select a job role first in Upload & Select tab.")
#                 else:
#                     with st.spinner("Optimizing your resume..."):
#                         rw      = rewrite_resume(role)
#                         jd      = JDS.get(role, role)
#                         after   = compute_score(rw, jd)
#                         ng      = keyword_gap(rw, jd)
#                         st.session_state.rewritten   = rw
#                         st.session_state.after_score = after
#                         st.session_state.new_gaps    = ng
#                     st.success(f"✅ Optimized! New score: **{round(after*100,1)}%**")
# 
#         if 'rewritten' in st.session_state:
#             st.markdown("---")
#             b   = st.session_state.before_score
#             a   = st.session_state.after_score
#             imp = round(((a-b)/b)*100,1) if b>0 else 0
#             st.markdown(f"""
#             <div style='background:linear-gradient(90deg,rgba(0,255,178,.07),rgba(0,212,255,.07));
#                 border:1px solid #00ffb2;border-radius:10px;padding:.8rem 1.2rem;
#                 display:flex;justify-content:space-between;margin-bottom:.8rem'>
#                 <span style='color:#ff4d6d;font-family:Syne;font-size:1.1rem;font-weight:700'>Before: {round(b*100,1)}%</span>
#                 <span style='color:#ffd166;font-family:Syne;font-size:1.1rem;font-weight:700'>⬆ +{imp}% Improved</span>
#                 <span style='color:#00ffb2;font-family:Syne;font-size:1.1rem;font-weight:700'>After: {round(a*100,1)}%</span>
#             </div>""", unsafe_allow_html=True)
# 
#             ng = st.session_state.get('new_gaps',[])
#             if ng:
#                 tags = " ".join([f'<span class="keyword-tag kw-add">✓ {w}</span>' for w,_ in ng[:8]])
#                 st.markdown(f'<div style="margin-bottom:.7rem"><span style="color:#6a8aaa;font-size:.82rem">Keywords added: </span>{tags}</div>',
#                              unsafe_allow_html=True)
# 
#             st.markdown(f'<div class="resume-output">{st.session_state.rewritten}</div>',
#                          unsafe_allow_html=True)
#             st.markdown("<br>", unsafe_allow_html=True)
# 
#             role = st.session_state.get('selected_role','General')
#             d1, d2, d3 = st.columns(3)
#             with d1:
#                 st.download_button("⬇️ Download PDF",
#                                     data=make_pdf(st.session_state.rewritten, role),
#                                     file_name="optimized_resume.pdf",
#                                     mime="application/pdf", use_container_width=True)
#             with d2:
#                 st.download_button("⬇️ Download MD",
#                                     data=st.session_state.rewritten,
#                                     file_name="optimized_resume.md",
#                                     mime="text/markdown", use_container_width=True)
#             with d3:
#                 st.download_button("⬇️ Download TXT",
#                                     data=st.session_state.rewritten,
#                                     file_name="optimized_resume.txt",
#                                     mime="text/plain", use_container_width=True)
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # TAB 4 — DASHBOARD
# # ══════════════════════════════════════════════════════════════════════════════
# with tab4:
#     st.markdown('<div class="section-title">📈 Analytics Dashboard</div>', unsafe_allow_html=True)
# 
#     if 'before_score' not in st.session_state:
#         st.markdown('<div class="info-box" style="text-align:center;padding:2.5rem">Complete analysis and optimization steps to see your dashboard.</div>',
#                      unsafe_allow_html=True)
#     else:
#         b      = st.session_state.before_score
#         a      = st.session_state.get('after_score', None)
#         resume = st.session_state.get('resume_text','')
#         jd     = st.session_state.get('jd_text','')
#         role   = st.session_state.get('selected_role','—')
# 
#         # KPI cards
#         k1, k2, k3, k4 = st.columns(4)
#         role_short = role.replace('INFORMATION-TECHNOLOGY','IT').replace('BUSINESS-DEVELOPMENT','BIZ-DEV')[:12]
#         with k1: st.markdown(f'<div class="metric-card"><div class="metric-value">{len(resume.split())}</div><div class="metric-label">Resume Words</div></div>', unsafe_allow_html=True)
#         with k2: st.markdown(f'<div class="metric-card"><div class="metric-value">{role_short}</div><div class="metric-label">Target Role</div></div>', unsafe_allow_html=True)
#         with k3: st.markdown(f'<div class="metric-card"><div class="score-before">{round(b*100,1)}%</div><div class="metric-label">Before Score</div></div>', unsafe_allow_html=True)
#         with k4:
#             if a:
#                 imp = round(((a-b)/b)*100,1) if b>0 else 0
#                 st.markdown(f'<div class="metric-card"><div class="score-after">+{imp}%</div><div class="metric-label">Improvement</div></div>', unsafe_allow_html=True)
#             else:
#                 st.markdown(f'<div class="metric-card"><div class="metric-value">—</div><div class="metric-label">Run Optimizer</div></div>', unsafe_allow_html=True)
# 
#         st.markdown("<br>", unsafe_allow_html=True)
#         ch1, ch2 = st.columns(2)
# 
#         with ch1:
#             if a: st.plotly_chart(comparison_chart(b, a), use_container_width=True)
#             else: st.plotly_chart(gauge(b, "Current Score", "#ff4d6d"), use_container_width=True)
# 
#         with ch2:
#             if jd:
#                 rw = set(clean_text(resume).split()); jw = set(clean_text(jd).split())
#                 matched = len(rw & jw); missing = len(jw - rw); extra = len(rw - jw)
#                 fig = go.Figure(go.Pie(
#                     labels=['Matched Keywords','Missing from Resume','Resume-Only'],
#                     values=[matched, missing, extra], hole=0.52,
#                     marker_colors=['#00ffb2','#ff4d6d','#00d4ff'],
#                     textfont=dict(family='DM Sans',color='white',size=10)
#                 ))
#                 fig.update_layout(title=dict(text='Keyword Overlap Analysis',font=dict(color='#6a8aaa',size=12,family='Syne')),
#                                    paper_bgcolor='rgba(0,0,0,0)',font=dict(color='#6a8aaa',family='DM Sans'),
#                                    legend=dict(font=dict(color='#6a8aaa')),
#                                    margin=dict(t=50,b=10,l=10,r=10),height=300)
#                 st.plotly_chart(fig, use_container_width=True)
# 
#         # Keyword frequency bar
#         if jd:
#             st.markdown("---")
#             st.markdown('<div class="section-title">🔑 JD Keyword Frequency</div>', unsafe_allow_html=True)
#             jd_freq = Counter(clean_text(jd).split()).most_common(15)
#             words = [w for w,_ in jd_freq]; counts = [c for _,c in jd_freq]
#             r_set = set(clean_text(resume).split())
#             bar_colors = ['#00ffb2' if w in r_set else '#ff4d6d' for w in words]
#             fig3 = go.Figure(go.Bar(x=counts, y=words, orientation='h',
#                                      marker_color=bar_colors, marker_line_width=0,
#                                      text=counts, textposition='outside',
#                                      textfont=dict(color='#c0d4e8',size=9)))
#             fig3.update_layout(
#                 title=dict(text='Green = In Resume  |  Red = Missing from Resume',
#                            font=dict(color='#6a8aaa',size=12,family='DM Sans')),
#                 paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',
#                 font=dict(family='DM Sans',color='#6a8aaa'),
#                 xaxis=dict(gridcolor='#162840',title='Frequency'),yaxis=dict(title=''),
#                 margin=dict(t=50,b=30,l=140,r=50),height=400)
#             st.plotly_chart(fig3, use_container_width=True)
# 
#         # Model info
#         if model_data:
#             st.markdown("---")
#             st.markdown('<div class="section-title">🤖 Trained Model Info</div>', unsafe_allow_html=True)
#             m1, m2, m3, m4 = st.columns(4)
#             with m1: st.markdown(f'<div class="metric-card"><div class="metric-value">{model_data.get("accuracy",72.84)}%</div><div class="metric-label">Model Accuracy</div></div>', unsafe_allow_html=True)
#             with m2: st.markdown(f'<div class="metric-card"><div class="metric-value">RF</div><div class="metric-label">Random Forest</div></div>', unsafe_allow_html=True)
#             with m3: st.markdown(f'<div class="metric-card"><div class="metric-value">{len(model_data.get("classes",ROLES[1:]))}</div><div class="metric-label">Job Categories</div></div>', unsafe_allow_html=True)
#             with m4: st.markdown(f'<div class="metric-card"><div class="metric-value">5K</div><div class="metric-label">TF-IDF Features</div></div>', unsafe_allow_html=True)

from pyngrok import ngrok
import subprocess, time


# Replace "YOUR_NGROK_AUTHTOKEN" with your actual ngrok authtoken
ngrok.set_auth_token("3AIZPLqaE4WY8tLRPjZWqpfsXvZ_5XXaJkaRp9Q5pww7LRRX6")

# Start streamlit in background
proc = subprocess.Popen(
    ["streamlit", "run", "app.py",
     "--server.port=8501",
     "--server.headless=true"],
    stdout=subprocess.PIPE, stderr=subprocess.PIPE
)

time.sleep(4)

# Open public tunnel
tunnel = ngrok.connect(8501)
print("=" * 50)
print("🚀 App is LIVE at:")
print(tunnel.public_url)
print("=" * 50)

